backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"   # tempat file gambar disimpan di repo
public_folder: "/static/uploads" # URL gambar di situs

locale: "id"

collections:
  - name: "products"
    label: "Katalog Produk"
    label_singular: "Produk"
    files:
      - name: "produk"
        label: "Daftar Produk (Games + APK)"
        file: "content/products.json"
        format: "json"
        fields:
          - { label: "Nama", name: "name", widget: "string" }
          - { label: "Harga", name: "price", widget: "number" }
          - { label: "Gambar", name: "image", widget: "image" }
          - { label: "Kategori", name: "category", widget: "string" }

  - name: "promos"
    label: "Promo"
    files:
      - name: "promo"
        label: "Daftar Promo"
        file: "content/promos.json"
        format: "json"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Deskripsi", name: "description", widget: "text" }
