backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"   # folder penyimpanan gambar di repo (opsional)
public_folder: "/static/uploads" # URL publik gambar (opsional)

locale: "id"

collections:
  - name: "products"
    label: "Katalog Produk"
    label_singular: "Produk"
    files:
      - name: "produk"
        label: "Daftar Produk (Games + APK)"
        file: "content/products.json"
        format: "json"
        fields:
          - { label: "Nama",    name: "name",      widget: "string" }
          - { label: "Harga",   name: "price",     widget: "number" }
          - { label: "Kategori",name: "category",  widget: "string" }
          - { label: "Gambar",  name: "imageURL",  widget: "string" }
          - { label: "Status",  name: "status",    widget: "select", options: ["Active","Hidden"] }
          - { label: "Catatan", name: "notes",     widget: "text", required: false }
